# Get all users
GET http://localhost:3000/api/users

###

GET http://localhost:3000/api/projects

###

DELETE  http://localhost:3000/api/projects
###

GET http://localhost:3000/api/education

###

DELETE  http://localhost:3000/api/education

###


GET http://localhost:3000/api/services

###

DELETE  http://localhost:3000/api/services

###


GET http://localhost:3000/api/contacts